package com.jobmatcher.server.model;

public enum ErrorCode {
    AUTH_INVALID,
    EMAIL_EXISTS,
    RESOURCE_NOT_FOUND,
    DATABASE_ERROR,
    INTERNAL_ERROR,
    VALIDATION_FAILED,
    METHOD_NOT_ALLOWED,
    PASSWORD_RECOVERY_FAILED,
    EMAIL_SENDING_FAILED,
    GMAIL_API_ERROR,
    TOKEN_CREATION_FAILED
}
